# Generated by Django 5.2.5 on 2025-08-19 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airport_system.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='airport_system.airport'),
        ),
    ]
