# Generated by Django 5.2.5 on 2025-08-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
    ]
