# Generated by Django 5.2.5 on 2025-08-19 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0005_remove_ticket_flight_remove_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airport_system.flight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport_system.order'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'flight'), name='unique seats for flight'),
        ),
    ]
