# Generated by Django 5.2.5 on 2025-09-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0009_alter_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(to='airport_system.crew'),
        ),
    ]
