# Generated by Django 5.2.5 on 2025-09-10 07:05

import airport_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0010_flight_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_system.models.create_custom_path),
        ),
    ]
