# Generated by Django 5.2.5 on 2025-09-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0011_airplane_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
