# Generated by Django 5.2.5 on 2025-09-10 09:20

import airport_system.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0012_alter_airplane_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport_system.models.create_custom_path),
        ),
    ]
