# Generated by Django 5.2.5 on 2025-09-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_system', '0014_alter_flight_crew_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport_system.order'),
        ),
    ]
